namespace NhutShop.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class UPDATEMODEL : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Footers", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Footers", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.Footers", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Footers", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.Footers", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.Footers", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.Footers", "Status", c => c.Boolean(nullable: false));
            AddColumn("dbo.MenuGroups", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.MenuGroups", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.MenuGroups", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.MenuGroups", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.MenuGroups", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.MenuGroups", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.MenuGroups", "Status", c => c.Boolean(nullable: false));
            AddColumn("dbo.Menus", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Menus", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.Menus", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Menus", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.Menus", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.Menus", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.OrderDetails", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.OrderDetails", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.OrderDetails", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.OrderDetails", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.OrderDetails", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.OrderDetails", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.OrderDetails", "Status", c => c.Boolean(nullable: false));
            AddColumn("dbo.Orders", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Orders", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.Orders", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.Orders", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.ProductCategories", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.ProductCategories", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.ProductCategories", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.ProductCategories", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.ProductCategories", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.ProductCategories", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.ProductCategories", "Status", c => c.Boolean(nullable: false));
            AddColumn("dbo.PostCategories", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.PostCategories", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.PostCategories", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.PostCategories", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.PostCategories", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.PostCategories", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.PostTags", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.PostTags", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.PostTags", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.PostTags", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.PostTags", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.PostTags", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.PostTags", "Status", c => c.Boolean(nullable: false));
            AddColumn("dbo.Tags", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Tags", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.Tags", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Tags", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.Tags", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.Tags", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.Tags", "Status", c => c.Boolean(nullable: false));
            AddColumn("dbo.ProductTags", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.ProductTags", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.ProductTags", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.ProductTags", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.ProductTags", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.ProductTags", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.ProductTags", "Status", c => c.Boolean(nullable: false));
            AddColumn("dbo.Slides", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.Slides", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.Slides", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.Slides", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.Slides", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.Slides", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.SupportOnlines", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.SupportOnlines", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.SupportOnlines", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.SupportOnlines", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.SupportOnlines", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.SupportOnlines", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.SystemConfigs", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.SystemConfigs", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.SystemConfigs", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.SystemConfigs", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.SystemConfigs", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.SystemConfigs", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.SystemConfigs", "Status", c => c.Boolean(nullable: false));
            AddColumn("dbo.VisitorStatistics", "CreatedDate", c => c.DateTime());
            AddColumn("dbo.VisitorStatistics", "CreatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.VisitorStatistics", "UpdatedDate", c => c.DateTime());
            AddColumn("dbo.VisitorStatistics", "UpdatedBy", c => c.String(maxLength: 270));
            AddColumn("dbo.VisitorStatistics", "MetaKeyword", c => c.String(maxLength: 270));
            AddColumn("dbo.VisitorStatistics", "MetaDescription", c => c.String(maxLength: 270));
            AddColumn("dbo.VisitorStatistics", "Status", c => c.Boolean(nullable: false));
            AlterColumn("dbo.Orders", "CreatedBy", c => c.String(maxLength: 270));
        }
        
        public override void Down()
        {
            AlterColumn("dbo.Orders", "CreatedBy", c => c.String());
            DropColumn("dbo.VisitorStatistics", "Status");
            DropColumn("dbo.VisitorStatistics", "MetaDescription");
            DropColumn("dbo.VisitorStatistics", "MetaKeyword");
            DropColumn("dbo.VisitorStatistics", "UpdatedBy");
            DropColumn("dbo.VisitorStatistics", "UpdatedDate");
            DropColumn("dbo.VisitorStatistics", "CreatedBy");
            DropColumn("dbo.VisitorStatistics", "CreatedDate");
            DropColumn("dbo.SystemConfigs", "Status");
            DropColumn("dbo.SystemConfigs", "MetaDescription");
            DropColumn("dbo.SystemConfigs", "MetaKeyword");
            DropColumn("dbo.SystemConfigs", "UpdatedBy");
            DropColumn("dbo.SystemConfigs", "UpdatedDate");
            DropColumn("dbo.SystemConfigs", "CreatedBy");
            DropColumn("dbo.SystemConfigs", "CreatedDate");
            DropColumn("dbo.SupportOnlines", "MetaDescription");
            DropColumn("dbo.SupportOnlines", "MetaKeyword");
            DropColumn("dbo.SupportOnlines", "UpdatedBy");
            DropColumn("dbo.SupportOnlines", "UpdatedDate");
            DropColumn("dbo.SupportOnlines", "CreatedBy");
            DropColumn("dbo.SupportOnlines", "CreatedDate");
            DropColumn("dbo.Slides", "MetaDescription");
            DropColumn("dbo.Slides", "MetaKeyword");
            DropColumn("dbo.Slides", "UpdatedBy");
            DropColumn("dbo.Slides", "UpdatedDate");
            DropColumn("dbo.Slides", "CreatedBy");
            DropColumn("dbo.Slides", "CreatedDate");
            DropColumn("dbo.ProductTags", "Status");
            DropColumn("dbo.ProductTags", "MetaDescription");
            DropColumn("dbo.ProductTags", "MetaKeyword");
            DropColumn("dbo.ProductTags", "UpdatedBy");
            DropColumn("dbo.ProductTags", "UpdatedDate");
            DropColumn("dbo.ProductTags", "CreatedBy");
            DropColumn("dbo.ProductTags", "CreatedDate");
            DropColumn("dbo.Tags", "Status");
            DropColumn("dbo.Tags", "MetaDescription");
            DropColumn("dbo.Tags", "MetaKeyword");
            DropColumn("dbo.Tags", "UpdatedBy");
            DropColumn("dbo.Tags", "UpdatedDate");
            DropColumn("dbo.Tags", "CreatedBy");
            DropColumn("dbo.Tags", "CreatedDate");
            DropColumn("dbo.PostTags", "Status");
            DropColumn("dbo.PostTags", "MetaDescription");
            DropColumn("dbo.PostTags", "MetaKeyword");
            DropColumn("dbo.PostTags", "UpdatedBy");
            DropColumn("dbo.PostTags", "UpdatedDate");
            DropColumn("dbo.PostTags", "CreatedBy");
            DropColumn("dbo.PostTags", "CreatedDate");
            DropColumn("dbo.PostCategories", "MetaDescription");
            DropColumn("dbo.PostCategories", "MetaKeyword");
            DropColumn("dbo.PostCategories", "UpdatedBy");
            DropColumn("dbo.PostCategories", "UpdatedDate");
            DropColumn("dbo.PostCategories", "CreatedBy");
            DropColumn("dbo.PostCategories", "CreatedDate");
            DropColumn("dbo.ProductCategories", "Status");
            DropColumn("dbo.ProductCategories", "MetaDescription");
            DropColumn("dbo.ProductCategories", "MetaKeyword");
            DropColumn("dbo.ProductCategories", "UpdatedBy");
            DropColumn("dbo.ProductCategories", "UpdatedDate");
            DropColumn("dbo.ProductCategories", "CreatedBy");
            DropColumn("dbo.ProductCategories", "CreatedDate");
            DropColumn("dbo.Orders", "MetaDescription");
            DropColumn("dbo.Orders", "MetaKeyword");
            DropColumn("dbo.Orders", "UpdatedBy");
            DropColumn("dbo.Orders", "UpdatedDate");
            DropColumn("dbo.OrderDetails", "Status");
            DropColumn("dbo.OrderDetails", "MetaDescription");
            DropColumn("dbo.OrderDetails", "MetaKeyword");
            DropColumn("dbo.OrderDetails", "UpdatedBy");
            DropColumn("dbo.OrderDetails", "UpdatedDate");
            DropColumn("dbo.OrderDetails", "CreatedBy");
            DropColumn("dbo.OrderDetails", "CreatedDate");
            DropColumn("dbo.Menus", "MetaDescription");
            DropColumn("dbo.Menus", "MetaKeyword");
            DropColumn("dbo.Menus", "UpdatedBy");
            DropColumn("dbo.Menus", "UpdatedDate");
            DropColumn("dbo.Menus", "CreatedBy");
            DropColumn("dbo.Menus", "CreatedDate");
            DropColumn("dbo.MenuGroups", "Status");
            DropColumn("dbo.MenuGroups", "MetaDescription");
            DropColumn("dbo.MenuGroups", "MetaKeyword");
            DropColumn("dbo.MenuGroups", "UpdatedBy");
            DropColumn("dbo.MenuGroups", "UpdatedDate");
            DropColumn("dbo.MenuGroups", "CreatedBy");
            DropColumn("dbo.MenuGroups", "CreatedDate");
            DropColumn("dbo.Footers", "Status");
            DropColumn("dbo.Footers", "MetaDescription");
            DropColumn("dbo.Footers", "MetaKeyword");
            DropColumn("dbo.Footers", "UpdatedBy");
            DropColumn("dbo.Footers", "UpdatedDate");
            DropColumn("dbo.Footers", "CreatedBy");
            DropColumn("dbo.Footers", "CreatedDate");
        }
    }
}
